/**
 * Lets a development build and a release build of Toph stay installed side by side on Android.
 *
 * Both builds come from the same generated native project, so the split follows the build type
 * rather than anything read at prebuild time: Android's debug build type installs under a `.dev`
 * application id with a "Dev" label, while release keeps the real identity. Moving between
 * `pnpm android` and `pnpm release:android` therefore never needs a fresh prebuild.
 *
 * The label is a manifest placeholder the build fills in, read by the launcher-facing name.
 *
 * Links are split the same way. The main manifest, which debug builds use as is, answers the
 * development scheme (`toph-dev`) and Expo's dev-client scheme (`exp+toph`); a generated
 * release-only manifest removes that link filter and answers the real scheme (`toph`) instead. A
 * `toph://` link therefore only ever opens the release build. The dev-client scheme stays in the
 * main manifest because the Expo CLI reads it from there when it launches a development build.
 *
 * Each install has its own sandbox, so the development build's data never touches the release
 * build's.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { type ConfigPlugin, withAndroidManifest, withAppBuildGradle } from 'expo/config-plugins.js';

export const DEV_ID_SUFFIX = '.dev';

/** The manifest placeholder the Android application label reads, set per build type. */
export const LABEL_PLACEHOLDER = 'appLabel';

export const devName = (name: string): string => `${name} Dev`;

export const devScheme = (scheme: string): string => `${scheme}-dev`;

/** Where Gradle reads the release build type's manifest, relative to the Android project. */
export const RELEASE_MANIFEST = 'app/src/release/AndroidManifest.xml';

interface Attributes {
  readonly $: Record<string, string | undefined>;
}

/** An `<intent-filter>` as Expo's manifest parser shapes it. */
export interface LinkFilter {
  readonly action?: Attributes[];
  readonly category?: Attributes[];
  readonly data?: Attributes[];
}

const schemeOf = (data: Attributes): string | undefined => data.$['android:scheme'];

/**
 * Moves the activity's link filter from the real scheme to the development one, in place, and
 * returns it. Running it again finds the filter by its development scheme and changes nothing.
 */
export const moveLinkSchemeToDev = (filters: readonly LinkFilter[], scheme: string): LinkFilter => {
  const answers = (filter: LinkFilter, candidate: string) =>
    filter.data?.some((data) => schemeOf(data) === candidate) === true;
  const filter =
    filters.find((candidate) => answers(candidate, scheme)) ??
    filters.find((candidate) => answers(candidate, devScheme(scheme)));
  if (filter === undefined) {
    throw new Error(`dev-variant: MainActivity has no intent filter for the "${scheme}" scheme`);
  }
  for (const data of filter.data ?? []) {
    if (schemeOf(data) === scheme) {
      data.$['android:scheme'] = devScheme(scheme);
    }
  }
  return filter;
};

const xmlAttribute = (value: string): string =>
  value
    .replaceAll('&', '&amp;')
    .replaceAll('"', '&quot;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');

const renderElements = (tag: string, elements: readonly Attributes[] | undefined, indent: string) =>
  (elements ?? []).map((element) => {
    const attributes = Object.entries(element.$)
      .filter((entry): entry is [string, string] => entry[1] !== undefined)
      .map(([key, value]) => ` ${key}="${xmlAttribute(value)}"`)
      .join('');
    return `${indent}<${tag}${attributes}/>`;
  });

const renderFilter = (filter: LinkFilter, opening: string): string => {
  const indent = '        ';
  return [
    `      ${opening}`,
    ...renderElements('action', filter.action, indent),
    ...renderElements('category', filter.category, indent),
    ...renderElements('data', filter.data, indent),
    '      </intent-filter>',
  ].join('\n');
};

/**
 * The release build type's manifest: it removes the development link filter, matched by its exact
 * content as the manifest merger requires, and declares the same filter for the real scheme alone.
 */
export const releaseManifest = (activity: string, devFilter: LinkFilter, scheme: string): string =>
  [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<!-- Generated by plugins/dev-variant.ts at prebuild. -->',
    '<manifest xmlns:android="http://schemas.android.com/apk/res/android"',
    '    xmlns:tools="http://schemas.android.com/tools">',
    '  <application>',
    `    <activity android:name="${xmlAttribute(activity)}">`,
    renderFilter(devFilter, '<intent-filter tools:node="remove">'),
    renderFilter({ ...devFilter, data: [{ $: { 'android:scheme': scheme } }] }, '<intent-filter>'),
    '    </activity>',
    '  </application>',
    '</manifest>',
    '',
  ].join('\n');

const groovyString = (value: string): string =>
  `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;

/**
 * Gives the app's `build.gradle` a default label and a debug build type with the development
 * suffix and label. React Native derives `debugOptimized` from `debug` with `initWith`, so it
 * inherits both.
 */
export const applyAndroidBuildTypes = (gradle: string, name: string): string => {
  if (gradle.includes('applicationIdSuffix')) {
    return gradle;
  }
  const defaultConfig = /(defaultConfig\s*\{)/u;
  const debugBuildType = /(buildTypes\s*\{\s*debug\s*\{)/u;
  if (!defaultConfig.test(gradle) || !debugBuildType.test(gradle)) {
    throw new Error('dev-variant: app/build.gradle has no defaultConfig or buildTypes.debug block');
  }
  const label = (value: string) =>
    `manifestPlaceholders['${LABEL_PLACEHOLDER}'] = ${groovyString(value)}`;
  return gradle
    .replace(defaultConfig, `$1\n        ${label(name)}`)
    .replace(
      debugBuildType,
      `$1\n            applicationIdSuffix '${DEV_ID_SUFFIX}'\n            ${label(devName(name))}`,
    );
};

const withDevVariant: ConfigPlugin = (config) => {
  const { name, scheme } = config;
  if (typeof scheme !== 'string') {
    throw new Error('dev-variant: app.json must set a single expo.scheme');
  }

  config = withAppBuildGradle(config, (mod) => {
    mod.modResults.contents = applyAndroidBuildTypes(mod.modResults.contents, name);
    return mod;
  });

  return withAndroidManifest(config, (mod) => {
    const [application] = mod.modResults.manifest.application ?? [];
    if (application === undefined) {
      throw new Error('dev-variant: AndroidManifest.xml has no application element');
    }
    application.$['android:label'] = `\${${LABEL_PLACEHOLDER}}`;

    const activityName = '.MainActivity';
    const activity = application.activity?.find(
      (candidate) => candidate.$['android:name'] === activityName,
    );
    if (activity === undefined) {
      throw new Error('dev-variant: AndroidManifest.xml has no MainActivity');
    }
    const devFilter = moveLinkSchemeToDev(activity['intent-filter'] ?? [], scheme);

    // The release manifest is derived from the filter edited just above, so it is written here
    // rather than in a separate mod that could run against a different version of the manifest.
    const target = join(mod.modRequest.platformProjectRoot, RELEASE_MANIFEST);
    mkdirSync(join(target, '..'), { recursive: true });
    writeFileSync(target, releaseManifest(activityName, devFilter, scheme));
    return mod;
  });
};

export default withDevVariant;
